export const MSG_ADD_TO_CART_SUCCESS = 'Thêm sản phẩm thành công !!'
export const MSG_UPDATE_CART_SUCCESS = 'Cập nhập giỏ hàng thành công !!'
export const MSG_DELETE_PRODUCT_IN_CART_SUCCESS = 'Xoá sản phẩm thành công !!'
export const MSG_CART_EMPTY = 'Chưa có sản phẩm nào trong giỏ hàng !!'
export const MSG_WELCOME = 'Chào bạn đến với VIETSUBTEAM !!'
